name: Build Lede

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Space cleanup
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
          sudo -E apt -y autoremove --purge
          sudo -E apt clean
          df -h
          
      - name: Initialization environment
        run: |
          sudo -E apt -y update
          sudo -E apt full-upgrade -y
          sudo -E apt -y install $(cat depends)
          
      - name: Clone source code
        run: |
          git clone -b 20221001 https://github.com/coolsnowwolf/lede
          
      - name: Update feeds
        run: cd lede && ./scripts/feeds update -a
        
      - name: Install feeds
        run: cd lede && ./scripts/feeds install -a
        
      - name: Make menuconfig
        uses: P3TERX/ssh2actions@main
          
      - name: Compile the firmware
        run: cd lede && make download -j8 && make V=s -j1
        
      - name: Prepare artifact
        run: | 
          mkdir -p ./artifact/firmware
          cp ./lede/bin/targets/*/*/*.* ./artifact/firmware/
          
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./artifact/firmware/
       
